spring:
  application:
    name: inventory-service
  profiles:
    active: local
server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    healthcheck:
      enabled: true

logging:
  level:
    org:
      springframework: DEBUG

app:
  lang: "Groovy!"

