spring:
  application:
    name: inventory-service
  profiles:
    active: local
server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    healthcheck:
      enabled: true

logging:
  level:
    org:
      springframework: DEBUG

app:
  lang: "Groovy!"


---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.202.128.102:8761/eureka/
